[package]
name = "leptos_integration_utils"
version = { workspace = true }
edition = "2021"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/leptos-rs/leptos"
description = "Utilities to help build server integrations for the Leptos web framework."

[dependencies]
futures = "0.3"
leptos = { workspace = true, features = ["ssr"] }
leptos_hot_reload = { workspace = true }
leptos_meta = { workspace = true, features = ["ssr"] }
leptos_config = { workspace = true }
tracing = "0.1.37"
serde_qs = "0.12"
serde = { version = "1", features = ["derive"] }
url = "2.4"
http = "0.2.11"
regex = "1.7.0"

[features]
experimental-islands = []
